services:
  web:
    image: 058264177299.dkr.ecr.ap-southeast-1.amazonaws.com/app-frontend:latest
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    command: npm start
    environment:
      - PORT=${WEB_PORT}
      - API_HOST=${API_HOST}
    network_mode: host
    depends_on:
      - api    
    restart: unless-stopped

  api:
    image: 058264177299.dkr.ecr.ap-southeast-1.amazonaws.com/app-backend:latest
    ports:
      - 8081:8081
    command: npm start
    environment:
      - PORT=8081:8081
      - DB=${API_DB}
    network_mode: host
    restart: unless-stopped
  
