on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-actions@v6
        with:
          context: ./api
          push: true
          tags: tilshansanoj/github-actions-test:latest, tilshansanoj/github-actions-test:${{ github.run_number }}